# Generated by Django 3.0.2 on 2020-01-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_friend_current_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
