# Generated by Django 3.0.2 on 2020-01-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
